project:
  type: website
  render: 
    - "*.qmd"

website:
  title: "Posit Cheat Sheets"
  navbar:
    left:
      - href: index.qmd
        text: HTML Cheat Sheets
      - href: pdf-cheatsheets.qmd
        text: PDF Cheat Sheets
format:
  html:
    theme:
      light: [flatly, html/css/style.scss]
      dark: [darkly, html/css/style.scss]
    toc: true
    toc-location: left
    highlight-style: a11y-dark
    css: html/css/cheatsheet.css
    mainfont: "Atkinson Hyperlegible"
    
editor: visual

execute: 
  freeze: auto
