project:
  type: website
  render: 
    - "*.qmd"

website:
  title: "Cheatsheets"
  navbar:
    left:
      - href: index.qmd
      - href: contributed-cheatsheets.qmd
      - href: translations.qmd
    right:
      - icon: github
        href: https://github.com/rstudio/cheatsheets
        aria-label: GitHub
  repo-url: https://github.com/rstudio/cheatsheets
  repo-actions: [edit, issue]
  
format:
  html:
    theme: [flatly, html/css/style.scss]
    toc: true
    toc-location: left
    highlight-style: a11y-dark
    css: html/css/cheatsheet.css
    mainfont: "Atkinson Hyperlegible"
    
editor: visual

execute: 
  freeze: auto
